# Generated by Django 3.1.2 on 2021-05-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=75)),
                ('lastName', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('questions', models.TextField(blank=True, max_length=450)),
            ],
        ),
    ]
