# Generated by Django 3.1.2 on 2021-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
