# Generated by Django 3.1.2 on 2021-05-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneFootage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('post', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('droneImage', models.ImageField(blank=True, null=True, upload_to='drone_images')),
                ('droneVideo', models.FileField(upload_to='drone_videos')),
            ],
        ),
    ]
