# Generated by Django 3.1.2 on 2021-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronefootage',
            name='droneVideo',
            field=models.FileField(blank=True, null=True, upload_to='drone_videos'),
        ),
    ]
